Improving html and moving styles to style.css
ok-technopolis-autumn-2019/Artyom-Petrov pull request #1
Opened 2019-10-02 21:19 UTC by akkalomator

2019-10-06 22:33 UTC, fromanywhere requested changes

2019-10-06 22:33 UTC, fromanywhere commented on style.css
> +.content__tasks__task-name {
Не стоит коммитить стили в рамках этого pr, например, потому, что здесь два правила из четырех навевают скепсис. В рамках допматериала можно почитать, какие побочные эффекты overflow: hidden может давать для display: inline и имеет ли смысл display: inline для float: left (но лучше дождаться лекции)

2019-10-06 22:33 UTC, fromanywhere commented on index.html
> +            <em class="heading__title">todos</em>
Здесь лучше использовать h1, потому что нам нужен заголовок. Казалось бы, есть header, это же наверное оно и есть? Но нет. Дело в том, что header (в общем случае) — это группирующий элемент, внутри него может быть не только заголовок сам по себе, но и вполне себе еще какие-нибудь элементы вроде навигации (https://developer.mozilla.org/ru/docs/Web/HTML/Element/header).

em не может вытащить на себе всю смысловую нагрузку заголовка. Его задача — поставить акцент, но не строить структуру документа.

Не то, чтобы в реальной жизни без этих соглашений было бы невозможно построить продукт, но в рамках нашего обучения лучше учитывать эти пожелания

2019-10-06 22:33 UTC, fromanywhere commented on index.html
> +                <label class="content__new-task_task">
label здесь избыточен, он просто оборачивает input по его размеру. В чем идея?

2019-10-06 22:33 UTC, fromanywhere commented on index.html
> +                    <input class="newtask" type="text" placeholder="What needs to be done?"/>
Здесь и дальше у читалок проблемы

2019-10-06 22:33 UTC, fromanywhere commented on index.html
> +                    <label class="content__tasks__task-check">
Здесь дискуссионное место. 
С одной стороны, с точки зрения опыта я бы тоже сделал вот ровно такую же конструкцию с label, которым оборачивается checkbox, потому что я знаю, как я потом сюда бы завозил стилевое оформление. Но даже в этом случае я бы писал классы и на чекбоксе.
С другой стороны, интересно было бы услышать Вашу мотивацию на такое решение

2019-10-06 22:33 UTC, fromanywhere commented on index.html
> +                    <button hidden="hidden">Delete</button>
hidden здесь плохо. И читалки не увидят, и отображение по наведению будет делать неудобно потом. Предлагается не скрывать сейчас кнопку вообще

2019-10-06 22:33 UTC, fromanywhere commented on index.html
> +            <div class="nav-menu">
Здесь лучше выделить логические группы у меню, плоским списком смысловая структура теряется

2019-10-06 22:33 UTC, fromanywhere commented on index.html
> +                <label class="nav-menu__items-left">3 items left</label>
Зачем здесь label?

2019-10-06 22:33 UTC, fromanywhere commented on index.html
> +                <button class="nav-menu__show-active">Active</button>
Здесь потерян один пункт из макета. Очень важно внимательно смотреть макет, это прям критерий профессионализма номер ноль

2019-10-06 22:33 UTC, fromanywhere commented on index.html
>  <!DOCTYPE html>
Было неплохо, стало лучше, но есть, куда расти

2019-10-09 11:17 UTC, akkalomator commented on style.css
> +.content__tasks__task-name {
Так, я почитаю, что к чему. Немного подправил стили, но удалять файл, наверное, уже не буду, раз он есть

2019-10-09 11:17 UTC, akkalomator commented on index.html
> +            <em class="heading__title">todos</em>
Да, согласен, неправ

2019-10-09 11:20 UTC, akkalomator commented on index.html
> +                <label class="content__new-task_task">
Если честно, webstorm подсветил как ворнинг. Я погулил - может, если в дальнейшем понадобится добавить что-то еще внутрь label, но сейчас действительно смысла нет

2019-10-09 11:22 UTC, akkalomator commented on index.html
> +                    <label class="content__tasks__task-check">
Подправил немного, положил текст задачи внутрь label - теперь можно помечать задачу как выполненную нажетием не только на сам checkbox, но и на текст

2019-10-09 11:22 UTC, akkalomator commented on index.html
> +                    <button hidden="hidden">Delete</button>
Ладно, исправлено

2019-10-09 11:22 UTC, akkalomator commented on index.html
> +            <div class="nav-menu">
Done

2019-10-09 11:22 UTC, akkalomator commented on index.html
> +                <label class="nav-menu__items-left">3 items left</label>
Просто div'a должно хватить

2019-10-09 11:23 UTC, akkalomator commented on index.html
> +                <button class="nav-menu__show-active">Active</button>
Усп...

2019-10-11 09:07 UTC, fromanywhere approved these changes

2019-10-11 10:17 UTC, merged