Applying styles to form
ok-technopolis-autumn-2019/Artyom-Petrov pull request #2
Opened 2019-10-15 08:45 UTC by akkalomator

2019-10-15 10:38 UTC, fromanywhere requested changes

2019-10-15 10:38 UTC, fromanywhere commented on index.html
> +                        <svg class="check-all-tick">
Интересное решение через инлайновый svg. Так можно, но только тогда нужно внимательнее брать svg из макета, а не рисовать руками

2019-10-15 10:38 UTC, fromanywhere commented on index.html
> +                            <input type="checkbox" class="content__tasks__task-check" />
Не, ну так теперь клик в текст выбирает галку, это не то, что ожидается

2019-10-15 10:38 UTC, fromanywhere commented on style.css
> +    outline: none;
Оставляем аутлайны для индикации фокуса

2019-10-15 10:38 UTC, fromanywhere commented on style.css
> +    height: auto;
переопределение высоты избыточно

2019-10-15 10:38 UTC, fromanywhere commented on style.css
> +    stroke: gray;
Да, вот это именно та сильная сторона инлайнового svg, за которую мы используем её в проде — можно хорошо сэкономить на ресурсах за счет стилизации в css

2019-10-15 10:38 UTC, fromanywhere commented on style.css
> +.content__new-task__check-all:hover svg polyline {
а вот здесь можно отстрелить себе в ногу, если появится вторая иконка с polyline

2019-10-15 10:38 UTC, fromanywhere commented on style.css
> +.content__tasks__task-check:checked + .checkbox-svg .checked-tick, .content__tasks__task-check:checked + .checkbox-svg {
Здесь по классам, это хорошо!

2019-10-15 10:38 UTC, fromanywhere commented on style.css
> +.content__tasks__task-check:checked + * + .content__tasks__task-text {
* опасно. Лучше подумать про ~

2019-10-15 10:38 UTC, fromanywhere commented on style.css
> +    position: absolute;
Хорошо!

2019-10-15 10:38 UTC, fromanywhere commented on style.css
> +    margin: 0 0 0 auto;
было бы хорошо, но только бессмысленно, там же родитель — флекс-контейнер, все разруливается на уровне flex-grow / flex-shrink

2019-10-15 10:38 UTC, fromanywhere commented on style.css
> +.nav-menu__filter-buttons__show-all:hover, .nav-menu__filter-buttons__show-active:hover, .nav-menu__filter-buttons__show-completed:hover {
Здесь не ховер, здесь текущий выбранный фильтр. Раз уж у Вас не радиокнопки, то придется сделать класс, который придется руками повесить на какую-то кнопку (например, первую), и потом предупредить js-разработчика, что этот класс нужно будет логикой переставлять между кнопками. Хорошо, когда js-разработчик понимает с полуслова, ну или это тот же человек

2019-10-15 10:38 UTC, fromanywhere commented on style.css
> +    text-decoration: underline;
Здесь не очень — это кнопка, а не ссылка. Плюс в карму за просмотр https://www.youtube.com/watch?v=MWJKwn_gKR4

2019-10-15 10:38 UTC, fromanywhere commented on style.css
>  }
Хороший старт, есть куда работать дальше

2019-10-15 10:56 UTC, akkalomator commented on index.html
> +                            <input type="checkbox" class="content__tasks__task-check" />
А при нажатии на текст, что должно происходить? Редактирование или как?

2019-10-15 12:00 UTC, fromanywhere commented on index.html
> +                            <input type="checkbox" class="content__tasks__task-check" />
Да, там заготовка под действие на редактирование. Как там конкретно будет меняться структура дерева под это, не готов сейчас говорить, оно может быть сделано очень по-разному. Но суть в том, что пространство зарезервировано да

2019-10-16 10:12 UTC, akkalomator commented on index.html
> +                            <input type="checkbox" class="content__tasks__task-check" />
Ок, пофиксил

2019-10-16 17:22 UTC, akkalomator commented on index.html
> +                        <svg class="check-all-tick">
Можно оставить как есть, или это критично в контексте задания?

2019-10-20 20:22 UTC, fromanywhere commented on index.html
> +                        <svg class="check-all-tick">
Ну вообще было бы конечно лучше экспортнуть svg-файл из фигмы, svg же — это xml, и тогда оно будет более честным

2019-10-20 20:36 UTC, fromanywhere commented
Значит ситуация такая — это первый PR, который похож на правду, поэтому я бы его проаппрувил, но всё равно есть еще пара доработок. 

Во-первых, есть прямо критическая бага 
![image](https://user-images.githubusercontent.com/1042969/67165715-467e4a80-f391-11e9-8dc2-df1619f04e7d.png)

Во-вторых, вот тут на ховер сомнительная обводка 
![image](https://user-images.githubusercontent.com/1042969/67165737-6f9edb00-f391-11e9-8435-727f43fe996b.png)

Пересмотрите, пожалуйста, детальнее правила по bem — нельзя там делать элементы у элементов, это прям антипаттерн (типа, content__new-task__check-all)

Из косметики — следует всё-таки серым фоном залить весь body, а не .wrapper. Паддинг у wrapper заодно уйдет. 

Я бы мог там цепляться еще за неудачный line-height у .heading__title, за лишние свойства вроде cursor: default;, но это уже если б Вы у меня стажировку проходили, а у нас же тут типа по лайту.
Специально спросил у Махнева, что он думает на всю эту тему, 
![image](https://user-images.githubusercontent.com/1042969/67165831-6a8e5b80-f392-11e9-8b00-19f3cfc16f9d.png)

2019-10-20 20:40 UTC, fromanywhere requested changes
up

2019-10-21 08:17 UTC, akkalomator commented
@fromanywhere 

> Во-вторых, вот тут на ховер сомнительная обводка
> ![image](https://user-images.githubusercontent.com/1042969/67165737-6f9edb00-f391-11e9-8435-727f43fe996b.png)

А что здесь не так? Хотел как-то отделить checkbox'ы от кнопки, как можно сделать по-другому? 

> Из косметики — следует всё-таки серым фоном залить весь body, а не .wrapper. Паддинг у wrapper заодно уйдет.

Это было сделано специально, у нас же получается форма, а не сайт, а так легче переносить будет (наверное), если понадобится

> Я бы мог там цепляться еще за неудачный line-height у .heading__title, за лишние свойства вроде cursor: default;, но это уже если б Вы у меня стажировку проходили, а у нас же тут типа по лайту.

cursor: default чтобы не было курсора-каретки при наведении на текст, который не предполагает взаимодействия.

Остальные замечания исправлены, подожду вашего ответа, доделаю и залью

2019-10-23 04:13 UTC, fromanywhere commented
> Остальные замечания исправлены, подожду вашего ответа, доделаю и залью

Лайк за способность аргументировать решения, принято

2019-10-23 04:13 UTC, fromanywhere approved these changes

2019-10-23 05:20 UTC, merged